class P204HANDSLISTvar {
  static List<String> NameList = [
    "PP-I002 – Outbound Process order ",
    "PP-I007 - Interface Update Status to PPIC",
    "PP-I008 - Inbound Production Confirm From TPPS System to SAP",
    "PP-I007 - Interface Update User Status  to QCFN",
    "PP-I008 - Inbound Production Confirm From TTPS System to SAP",
    "PP-I004 - Inbound Post Goods Receipt FG",
    "GAS",
    "PH",
    "ISN",
    "PVD",
    "PAL",
    "DELTA",
    "",
    "",
    "",
    "",
  ];

  static List<bool> isHoveredList = [
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
  ];
}
